namespace Logos.Input.Sdl3
{
    internal enum SDL_EventType : uint
    {
        SDL_EVENT_FIRST = 0,
        SDL_EVENT_QUIT = 0x100,
        
        // Window events
        SDL_EVENT_WINDOW_SHOWN              = 0x202,
        SDL_EVENT_WINDOW_HIDDEN             = 0x203,
        SDL_EVENT_WINDOW_EXPOSED            = 0x204,
        SDL_EVENT_WINDOW_MOVED              = 0x205,
        SDL_EVENT_WINDOW_RESIZED            = 0x206,
        SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED = 0x207,
        SDL_EVENT_WINDOW_METAL_VIEW_RESIZED = 0x208,
        SDL_EVENT_WINDOW_MINIMIZED          = 0x209,
        SDL_EVENT_WINDOW_MAXIMIZED          = 0x20A,
        SDL_EVENT_WINDOW_RESTORED           = 0x20B,
        SDL_EVENT_WINDOW_MOUSE_ENTER        = 0x20C,
        SDL_EVENT_WINDOW_MOUSE_LEAVE        = 0x20D,
        SDL_EVENT_WINDOW_FOCUS_GAINED       = 0x20E,
        SDL_EVENT_WINDOW_FOCUS_LOST         = 0x20F,
        SDL_EVENT_WINDOW_CLOSE_REQUESTED    = 0x210,
        SDL_EVENT_WINDOW_HIT_TEST           = 0x211,
        SDL_EVENT_WINDOW_ICCPROF_CHANGED    = 0x212,
        SDL_EVENT_WINDOW_DISPLAY_CHANGED    = 0x213,
        SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED = 0x214,
        SDL_EVENT_WINDOW_SAFE_AREA_CHANGED  = 0x215,
        SDL_EVENT_WINDOW_OCCLUDED           = 0x216,
        SDL_EVENT_WINDOW_ENTER_FULLSCREEN   = 0x217,
        SDL_EVENT_WINDOW_LEAVE_FULLSCREEN   = 0x218,
        SDL_EVENT_WINDOW_DESTROYED          = 0x219,
        SDL_EVENT_WINDOW_HDR_STATE_CHANGED  = 0x21A,
        
        // Keyboard Events
        SDL_EVENT_KEY_DOWN = 0x300,
        SDL_EVENT_KEY_UP,
        SDL_EVENT_KEYMAP_CHANGED,
        SDL_EVENT_KEYBOARD_ADDED,
        SDL_EVENT_KEYBOARD_REMOVED,

        // Mouse Events
        SDL_EVENT_MOUSE_MOTION,  // 0x400 according to the SDL docs
        SDL_EVENT_MOUSE_BUTTON_DOWN,
        SDL_EVENT_MOUSE_BUTTON_UP,
        SDL_EVENT_MOUSE_WHEEL,
        SDL_EVENT_MOUSE_ADDED,
        SDL_EVENT_MOUSE_REMOVED,
    }
}
